# Generated by Django 4.2.11 on 2024-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
    ]
