# Generated by Django 4.2.11 on 2024-04-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_concert_url_alter_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/static/images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/static/images'),
        ),
    ]
