# Generated by Django 4.2.11 on 2024-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/static/images/events'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='home/static/images/galerie'),
        ),
    ]
